In [1]:
import numpy as np

In [2]:
X_dot_W=np.array([[0,0,0],[10,10,10]])

In [3]:
B=np.array([1,2,3])

In [4]:
X_dot_W

array([[ 0,  0,  0],
       [10, 10, 10]])

In [5]:
X_dot_W+B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [6]:
dY=np.array([[1,2,3],[4,5,6]])

In [8]:
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
dB=np.sum(dY,axis=0)

In [12]:
dB

array([5, 7, 9])