In [1]:
import numpy as np

In [2]:
x=np.array([-1.0,1.0,2.0])

In [3]:
x

array([-1.,  1.,  2.])

In [4]:
y=x>0

In [5]:
y

array([False,  True,  True])

In [7]:
y=y.astype(np.int)

<ipython-input-7-a5f8035c8c15>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y=y.astype(np.int)


In [8]:
y

array([0, 1, 1])