In [1]:
import numpy as np

In [2]:
A=np.array([[1,2],[3,4]])

In [3]:
A.shape

(2, 2)

In [4]:
B=np.array([[5,6],[7,8]])

In [5]:
B.shape

(2, 2)

In [6]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [7]:
A=np.array([[1,2,3],[4,5,6]])

In [8]:
A.shape

(2, 3)

In [9]:
B=np.array([[1,2],[3,4],[5,6]])

In [10]:
B.shape

(3, 2)

In [11]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [13]:
A=np.array([[1,2],[3,4],[5,6]])

In [14]:
A.shape

(3, 2)

In [15]:
B=np.array([7,8])

In [16]:
B.shape

(2,)

In [17]:
np.dot(A,B)

array([23, 53, 83])