In [1]:
import numpy as np

In [2]:
a=np.array([1010,1000,990])

In [3]:
np.exp(a)/np.sum(np.exp(a))

<ipython-input-3-89710c4b0d3e>:1: RuntimeWarning: overflow encountered in exp
  np.exp(a)/np.sum(np.exp(a))
<ipython-input-3-89710c4b0d3e>:1: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a)/np.sum(np.exp(a))


array([nan, nan, nan])

In [4]:
c=np.max(a)

In [5]:
a-c

array([  0, -10, -20])

In [6]:
np.exp(a-c)/np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [7]:
def softmax(a):
    c=np.max(a)
    exp_a=np.exp(a-c)
    sum_exp_a=np.sum(exp_a)
    y=exp_a/sum_exp_a
    return y