In [6]:
import numpy as np
import function_2
import numerical_gradient

[0. 4.]
[6. 0.]


In [7]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    x_history = []

    for i in range(step_num):
        x_history.append(x.copy())
        grad = numerical_gradient.numerical_gradient(f, x)
        x -= lr * grad

    return x, np.array(x_history)

In [8]:
init_x = np.array([-3.0, 4.0])

In [10]:
gradient_descent(function_2.function_2, init_x=init_x, lr=0.1,step_num=100)

(array([-1.25592487e-19,  1.65436123e-19]),
 array([[-6.11110793e-10,  8.14814391e-10],
        [-4.88888634e-10,  6.51851512e-10],
        [-3.91110907e-10,  5.21481210e-10],
        [-3.12888726e-10,  4.17184968e-10],
        [-2.50310981e-10,  3.33747974e-10],
        [-2.00248785e-10,  2.66998379e-10],
        [-1.60199028e-10,  2.13598704e-10],
        [-1.28159222e-10,  1.70878963e-10],
        [-1.02527378e-10,  1.36703170e-10],
        [-8.20219022e-11,  1.09362536e-10],
        [-6.56175217e-11,  8.74900290e-11],
        [-5.24940174e-11,  6.99920232e-11],
        [-4.19952139e-11,  5.59936186e-11],
        [-3.35961711e-11,  4.47948948e-11],
        [-2.68769369e-11,  3.58359159e-11],
        [-2.15015495e-11,  2.86687327e-11],
        [-1.72012396e-11,  2.29349862e-11],
        [-1.37609917e-11,  1.83479889e-11],
        [-1.10087934e-11,  1.46783911e-11],
        [-8.80703469e-12,  1.17427129e-11],
        [-7.04562775e-12,  9.39417033e-12],
        [-5.63650220e-12,  7.515

In [11]:
init_x=np.array([-3.0,4.0])

In [12]:
gradient_descent(function_2.function_2, init_x=init_x, lr=0.1,step_num=100)

(array([-6.11110793e-10,  8.14814391e-10]),
 array([[-3.00000000e+00,  4.00000000e+00],
        [-2.40000000e+00,  3.20000000e+00],
        [-1.92000000e+00,  2.56000000e+00],
        [-1.53600000e+00,  2.04800000e+00],
        [-1.22880000e+00,  1.63840000e+00],
        [-9.83040000e-01,  1.31072000e+00],
        [-7.86432000e-01,  1.04857600e+00],
        [-6.29145600e-01,  8.38860800e-01],
        [-5.03316480e-01,  6.71088640e-01],
        [-4.02653184e-01,  5.36870912e-01],
        [-3.22122547e-01,  4.29496730e-01],
        [-2.57698038e-01,  3.43597384e-01],
        [-2.06158430e-01,  2.74877907e-01],
        [-1.64926744e-01,  2.19902326e-01],
        [-1.31941395e-01,  1.75921860e-01],
        [-1.05553116e-01,  1.40737488e-01],
        [-8.44424930e-02,  1.12589991e-01],
        [-6.75539944e-02,  9.00719925e-02],
        [-5.40431955e-02,  7.20575940e-02],
        [-4.32345564e-02,  5.76460752e-02],
        [-3.45876451e-02,  4.61168602e-02],
        [-2.76701161e-02,  3.689

In [13]:
init_x=np.array([-3.0,4.0])

In [14]:
gradient_descent(function_2.function_2, init_x=init_x, lr=0.1,step_num=100)

(array([-6.11110793e-10,  8.14814391e-10]),
 array([[-3.00000000e+00,  4.00000000e+00],
        [-2.40000000e+00,  3.20000000e+00],
        [-1.92000000e+00,  2.56000000e+00],
        [-1.53600000e+00,  2.04800000e+00],
        [-1.22880000e+00,  1.63840000e+00],
        [-9.83040000e-01,  1.31072000e+00],
        [-7.86432000e-01,  1.04857600e+00],
        [-6.29145600e-01,  8.38860800e-01],
        [-5.03316480e-01,  6.71088640e-01],
        [-4.02653184e-01,  5.36870912e-01],
        [-3.22122547e-01,  4.29496730e-01],
        [-2.57698038e-01,  3.43597384e-01],
        [-2.06158430e-01,  2.74877907e-01],
        [-1.64926744e-01,  2.19902326e-01],
        [-1.31941395e-01,  1.75921860e-01],
        [-1.05553116e-01,  1.40737488e-01],
        [-8.44424930e-02,  1.12589991e-01],
        [-6.75539944e-02,  9.00719925e-02],
        [-5.40431955e-02,  7.20575940e-02],
        [-4.32345564e-02,  5.76460752e-02],
        [-3.45876451e-02,  4.61168602e-02],
        [-2.76701161e-02,  3.689